(()=>{"use strict";
const api=window.nikaDesktop&&window.nikaDesktop.offline,$=id=>document.getElementById(id);
let state=null,cart=[];
const money=v=>new Intl.NumberFormat("ru-RU",{maximumFractionDigits:2}).format(Number(v||0))+" ₸";
const qty=v=>{const n=Number(v||0);return Number.isInteger(n)?String(n):n.toFixed(3).replace(/0+$/,"").replace(/\.$/,"")};
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
function toast(m){const n=$("toast");n.textContent=m;n.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.remove("show"),4200)}
function cache(name){return state&&state.cache&&Array.isArray(state.cache[name])?state.cache[name]:[]}
function search(rows,q){const n=String(q||"").trim().toLowerCase();if(!n)return rows;return rows.filter(r=>[r.name,r.barcode,r.gtin,r.ntin,r.category,r.full_name,r.company_name,r.phone,r.iin].some(v=>String(v||"").toLowerCase().includes(n)))}
function candidates(raw){const s=String(raw||"").trim(),out=new Set([s,s.replace(/^\]d2/i,"")]),compact=s.replace(/^\]d2/i,"").replace(/\x1d/g,"");out.add(compact);const m=compact.match(/^01(\d{14})/);if(m)out.add(m[1]);return Array.from(out).filter(Boolean)}
function findItem(code){const rows=[...cache("stock"),...cache("items")];for(const c of candidates(code)){const f=rows.find(r=>[r.barcode,r.gtin,r.ntin].some(v=>String(v||"")===c));if(f)return f}return null}
function price(i){return Number(i.retail_price??i.price??0)}
function stockFor(id){const r=cache("stock").find(x=>String(x.id)===String(id));return r?Number(r.stock??r.quantity??0):0}
function renderHeader(){const ready=state&&state.ready,s=state?state.sync_state:"offline";$("noIdentity").hidden=!!ready;$("identity").textContent=ready?[state.identity.company_name,state.identity.username].filter(Boolean).join(" · "):"";$("pendingTop").textContent=ready&&state.pending_count?"В очереди: "+state.pending_count:"";$("statusPill").textContent=s==="syncing"?"Синхронизация…":s==="synced"?"Синхронизировано":"Офлайн";$("statusPill").className="pill "+(s==="synced"?"ok":"")}
function add(item){const id=Number(item.id||0);if(!id)return;const e=cart.find(r=>Number(r.id)===id&&!r.excise_stamp);if(e)e.qty+=1;else cart.push({id,name:item.name||("Товар #"+id),price:price(item),retail_price:price(item),qty:1,unit:item.unit||"шт",gtin:item.gtin||"",ntin:item.ntin||"",item_type:item.item_type||"product"});renderCart();$("saleScan").focus()}
function renderSaleItems(){const rows=search(cache("items"),$("saleSearch").value).slice(0,60);$("saleItems").innerHTML=rows.length?rows.map(i=>`<div class="item" data-id="${esc(i.id)}"><div class="item-name">${esc(i.name||"Без названия")}</div><div class="item-meta">${money(price(i))} · остаток ${qty(stockFor(i.id))} ${esc(i.unit||"")}</div><div class="item-meta">${esc(i.barcode||i.gtin||"")}</div></div>`).join(""):'<div class="empty">Товары не найдены</div>';document.querySelectorAll("#saleItems [data-id]").forEach(n=>n.onclick=()=>{const i=cache("items").find(r=>String(r.id)===n.dataset.id);if(i)add(i)})}
function renderCart(){if(!cart.length){$("cart").innerHTML='<div class="empty">Корзина пустая</div>';$("cartTotal").textContent="Итого: 0 ₸";return}$("cart").innerHTML=cart.map((r,i)=>`<div class="cart-line"><div><b>${esc(r.name)}</b><div class="muted">${money(r.price)} / ${esc(r.unit)}</div></div><input class="qty" data-q="${i}" type="number" min="0.001" step="0.001" value="${r.qty}"><div><b>${money(r.price*r.qty)}</b></div><button class="btn danger" data-d="${i}">×</button></div>`).join("");$("cartTotal").textContent="Итого: "+money(cart.reduce((s,r)=>s+Number(r.price||0)*Number(r.qty||0),0));document.querySelectorAll("[data-q]").forEach(n=>n.onchange=()=>{const i=Number(n.dataset.q),v=Number(n.value||0);if(v>0&&cart[i])cart[i].qty=v;renderCart()});document.querySelectorAll("[data-d]").forEach(n=>n.onclick=()=>{cart.splice(Number(n.dataset.d),1);renderCart()})}
function selects(){const rows=cache("stock").filter(r=>["product","ingredient","semi_finished"].includes(String(r.item_type||"product"))),opts=rows.map(i=>`<option value="${esc(i.id)}">${esc(i.name)} · ${qty(i.stock)} ${esc(i.unit||"")}</option>`).join("");$("incomeItem").innerHTML=opts;$("writeoffItem").innerHTML=opts;$("incomeSupplier").innerHTML='<option value="">Без поставщика</option>'+cache("suppliers").map(s=>`<option value="${esc(s.id)}">${esc(s.name||"")}</option>`).join("");const pc=cache("clients").find(c=>String(c.company_name||c.full_name||"").trim().toLowerCase()==="частное лицо");$("saleClient").innerHTML=cache("clients").map(c=>`<option value="${esc(c.id)}" ${pc&&String(pc.id)===String(c.id)?"selected":""}>${esc(c.company_name||c.full_name||("Клиент #"+c.id))}</option>`).join("")}
function table(rows,cols){if(!rows.length)return'<div class="empty">Нет локальных данных</div>';return'<div style="overflow:auto"><table class="table"><thead><tr>'+cols.map(c=>"<th>"+esc(c[0])+"</th>").join("")+"</tr></thead><tbody>"+rows.map(r=>"<tr>"+cols.map(c=>"<td>"+(typeof c[1]==="function"?c[1](r):esc(r[c[1]]||""))+"</td>").join("")+"</tr>").join("")+"</tbody></table></div>"}
function renderCatalog(){$("catalogTable").innerHTML=table(search(cache("items"),$("catalogSearch").value).slice(0,500),[["Название",r=>esc(r.name||"")],["Штрихкод",r=>esc(r.barcode||r.gtin||"")],["Категория",r=>esc(r.category||"")],["Цена",r=>"<b>"+money(price(r))+"</b>"]])}
function renderStock(){$("stockTable").innerHTML=table(search(cache("stock"),$("stockSearch").value).slice(0,500),[["Товар",r=>esc(r.name||"")],["Остаток",r=>"<b>"+qty(r.stock)+" "+esc(r.unit||"")+"</b>"],["Закуп",r=>money(r.purchase_price)],["Розница",r=>money(r.retail_price)]])}
function renderClients(){$("clientsTable").innerHTML=table(cache("clients").slice(0,500),[["Клиент",r=>esc(r.company_name||r.full_name||"")],["ФИО",r=>esc(r.full_name||"")],["Телефон",r=>esc(r.phone||"")],["ИИН/БИН",r=>esc(r.iin||r.bin||"")]])}
function renderQueue(){const rows=state&&Array.isArray(state.queue)?state.queue:[];$("queueTable").innerHTML=table(rows,[["Время",r=>esc(new Date(r.created_at).toLocaleString("ru-RU"))],["Операция",r=>esc(r.operation_type||"")],["Статус",r=>esc(r.state||"")],["Попытки",r=>esc(r.attempts||0)],["Ошибка",r=>esc(r.last_error||"")]])}
function renderAll(){renderHeader();selects();renderSaleItems();renderCart();renderCatalog();renderStock();renderClients();renderQueue()}
async function refresh(){if(!api)return toast("Офлайн-модуль недоступен");state=await api.getState();renderAll()}
async function submit(path,body){const r=await api.submit({path,body});await refresh();return r||{}}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(n=>n.classList.remove("active"));document.querySelectorAll(".panel").forEach(n=>n.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active")});
$("saleSearch").oninput=renderSaleItems;$("catalogSearch").oninput=renderCatalog;$("stockSearch").oninput=renderStock;
$("saleScan").onkeydown=e=>{if(e.key!=="Enter")return;e.preventDefault();const raw=e.currentTarget.value;e.currentTarget.value="";const i=findItem(raw);if(!i)return toast("Код не найден в локальном каталоге. Новый код проверится после появления сети.");add(i)};
$("payBtn").onclick=async()=>{if(!cart.length)return toast("Корзина пустая");$("payBtn").disabled=true;try{const snapshot=cart.map(r=>({...r})),r=await submit("/sales/pay",{client_id:Number($("saleClient").value||0)||null,payment_method:$("salePayment").value,cart:snapshot,kaspi_transaction_id:"",kaspi_method:""});cart=[];renderCart();toast(r.queued?"Продажа сохранена в очередь. reKassa сработает после синхронизации.":r.fiscalized===false&&r.rekassa_required!==false?"Продажа на сервере, но reKassa пока не подтвердила чек.":"Продажа синхронизирована.")}catch(e){toast(e.message||"Не удалось сохранить продажу")}finally{$("payBtn").disabled=false}};
$("incomeBtn").onclick=async()=>{const item=Number($("incomeItem").value||0),q=Number($("incomeQty").value||0),p=Number($("incomePrice").value||0),supplier=Number($("incomeSupplier").value||0);if(!item||q<=0||p<0)return toast("Проверьте товар, количество и цену");$("incomeBtn").disabled=true;try{const r=await submit(supplier?"/api/mobile/stock/income/supplier":"/api/stock/income",{item_id:item,supplier_id:supplier||undefined,quantity:q,price:p,comment:$("incomeComment").value||"",update_retail:false});toast(r.queued?"Приход сохранён в очередь.":"Приход синхронизирован.");$("incomeQty").value="1";$("incomeComment").value=""}catch(e){toast(e.message||"Не удалось сохранить приход")}finally{$("incomeBtn").disabled=false}};
$("writeoffBtn").onclick=async()=>{const item=Number($("writeoffItem").value||0),q=Number($("writeoffQty").value||0);if(!item||q<=0)return toast("Проверьте товар и количество");$("writeoffBtn").disabled=true;try{const r=await submit("/api/stock/writeoff",{item_id:item,quantity:q,comment:$("writeoffComment").value||""});toast(r.queued?"Списание сохранено в очередь.":"Списание синхронизировано.");$("writeoffQty").value="1";$("writeoffComment").value=""}catch(e){toast(e.message||"Не удалось сохранить списание")}finally{$("writeoffBtn").disabled=false}};
$("syncBtn").onclick=async()=>{$("syncBtn").disabled=true;$("statusPill").textContent="Синхронизация…";try{state=await api.sync();renderAll();toast(state.sync_state==="synced"?"Синхронизация завершена":"Сервер пока недоступен. Работаем локально.")}finally{$("syncBtn").disabled=false}};
$("onlineBtn").onclick=()=>api.openOnline();
refresh().then(()=>$("saleScan").focus());
})();